# Generated by Django 5.0.7 on 2024-07-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
